// Teste das Requisições REST dos cliente
//@baseURL = http://localhost:4000/api/clientes
@baseURL  = https://backend-mongodb-pi.vercel.app/api/clientes

// GET - Lista todos os registros
GET {{baseURL}}
Content-Type: application/json

###
// GET - Lista um registro pelo id
GET {{baseURL}}/id/65148024dc6e34b97ffcb91b
Content-Type: application/json

###
// GET - Lista um registro pelo cpf
GET {{baseURL}}/cpf/12345678912
Content-Type: application/json

###
// GET - Lista um registro pela nome 
GET {{baseURL}}/nome/Fabio
Content-Type: application/json

###
//GET - Lista os resgistros com media salarial menor que o parametro e com 
//o numero de moradores igual o parametro
GET {{baseURL}}/salarioMenor/3000/5
Content-Type: application/json

###
//GET - Lista os resgistros com media salarial maior que o parametro e com 
//o numero de moradores igual o parametro
GET {{baseURL}}/salarioMaior/1000/5
Content-Type: application/json

###
// DELETE - Apaga um registro pelo id
DELETE {{baseURL}}/65119a864106380b59d79c07
Content-Type: application/json

###
// POST - Insere um novo registro
POST {{baseURL}}
Content-Type: application/json

{
    "cpf": "12345678912",
    "nome": "Alexandre Pedra",
    "moradores_residencia": 5 ,
    "telefone": "11111111111",
    "dtNasc": "2022-10-15",
    "medSalario": 2000.60
}

###
// PUT - Altera o registro
PUT {{baseURL}}
Content-Type: application/json

{
    "_id": "6511a2afb288a7d4c8dcc894",
    "cpf": "12345678912",
    "nome": "Fabio Alexandre",
    "moradores_residencia": 25,
    "telefone": "11111111111",
    "dtNasc": "2022-10-15",
    "medSalario": 3000
}

